title : Diogo Mónica's Personal Website
tagline:
author :
  name : Diogo Mónica
  email : diogo.monica@gmail.com
  github : diogomonica
  twitter : diogomonica
  feedburner : feedname

navigation :
  - archive.html
  - posts.html
